#!/bin/bash
cd tool && mvn -Dgpg.skip=true -Duser.name="Your Name" -Dmaven.test.skip=true -Dbootclasspath.compile=/usr/lib/jvm/java-6-openjdk-$1/jre/lib/rt.jar -Djava6.home=/usr/lib/jvm/java-6-openjdk-$1/jre -X
