#!/bin/bash
cd tool
mvn dependency:copy-dependencies
cd ../test-apex
ls *.g | xargs -n1 java -cp "../tool/target/classes:../tool/target/dependency/ST4-4.0.7-rc-1.jar:../tool/target/dependency/antlr-2.7.7.jar:../tool/target/dependency/antlr-runtime-3.5-SNAPSHOT.jar" org.antlr.Tool
ls *.cls | xargs -n1 cat
